import type {Metadata} from 'next';
import {Box, Theme} from '@radix-ui/themes';

import './globals.scss';
import {Navbar} from "@/components/Navbar/Navbar";
import React from "react";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang="en">
    <body>
    <Theme accentColor="crimson" grayColor="sand" radius="large">
      <Navbar/>
      <Box p="5">
        {children}
      </Box>
    </Theme>
    </body>
    </html>
  );
}
